import type { Conversa } from "@/lib/types";

/** Conversas mock do WhatsApp. Trocáveis por Supabase/WhatsApp API depois. */

export const CONVERSAS: Conversa[] = [
  {
    id: "cv1",
    contatoId: "c3",
    nome: "Patrícia Nunes",
    telefone: "(31) 98410-1190",
    ultimaHora: "14:38",
    naoLidas: 2,
    atendidoPor: "agente",
    agenteNome: "Ana",
    online: true,
    mensagens: [
      { id: "m1", autor: "cliente", texto: "Oi! Vi o anúncio de vocês e queria entender melhor os planos.", hora: "14:22" },
      { id: "m2", autor: "agente", texto: "Oi, Patrícia! Aqui é a Ana 👋 Que bom te ver por aqui. Você procura para uso próprio ou para a empresa?", hora: "14:23" },
      { id: "m3", autor: "cliente", texto: "Para a ConstruLar, somos umas 20 pessoas no comercial.", hora: "14:25" },
      { id: "m4", autor: "agente", texto: "Perfeito. Para times desse tamanho o plano Pro costuma encaixar bem. Qual é a maior dor de vocês hoje: organizar os contatos ou acompanhar as vendas?", hora: "14:26" },
      { id: "m5", autor: "cliente", texto: "Acompanhar as vendas, a gente perde negócio por falta de follow-up.", hora: "14:36" },
      { id: "m6", autor: "cliente", texto: "Consegue me mandar uma proposta?", hora: "14:38" },
    ],
  },
  {
    id: "cv2",
    contatoId: "c2",
    nome: "Bruno Menezes",
    telefone: "(21) 99145-8820",
    ultimaHora: "13:05",
    naoLidas: 0,
    atendidoPor: "humano",
    online: false,
    mensagens: [
      { id: "m1", autor: "cliente", texto: "Bom dia! Recebi a proposta, obrigado.", hora: "11:40" },
      { id: "m2", autor: "atendente", texto: "Bom dia, Bruno! Qualquer dúvida sobre os valores é só chamar.", hora: "11:42" },
      { id: "m3", autor: "cliente", texto: "Fechado, vou revisar com meu sócio e te retorno até sexta.", hora: "13:05" },
    ],
  },
  {
    id: "cv3",
    contatoId: "c6",
    nome: "Henrique Barros",
    telefone: "(51) 98122-7745",
    ultimaHora: "Ontem",
    naoLidas: 1,
    atendidoPor: "aguardando",
    online: false,
    mensagens: [
      { id: "m1", autor: "cliente", texto: "Vocês atendem na área da saúde?", hora: "Ontem 17:20" },
      { id: "m2", autor: "atendente", texto: "Atendemos sim, Henrique! Temos clientes em clínicas e farmácias.", hora: "Ontem 17:45" },
      { id: "m3", autor: "cliente", texto: "Legal. E o suporte é em português?", hora: "Ontem 18:02" },
    ],
  },
  {
    id: "cv4",
    contatoId: "c10",
    nome: "Thiago Souza",
    telefone: "(85) 99711-3308",
    ultimaHora: "Ontem",
    naoLidas: 0,
    atendidoPor: "agente",
    agenteNome: "Duda",
    online: false,
    mensagens: [
      { id: "m1", autor: "cliente", texto: "Qual a diferença entre o plano Starter e o Pro?", hora: "Ontem 09:10" },
      { id: "m2", autor: "agente", texto: "Ótima pergunta! O Starter cobre o essencial de contatos e pipeline. O Pro adiciona automações, relatórios avançados e os agentes de IA. Quer que eu te mande um comparativo?", hora: "Ontem 09:11" },
      { id: "m3", autor: "cliente", texto: "Pode mandar!", hora: "Ontem 09:12" },
      { id: "m4", autor: "agente", texto: "Enviado no seu e-mail 📩 Se quiser, marco uma demo rápida.", hora: "Ontem 09:12" },
    ],
  },
  {
    id: "cv5",
    contatoId: "c12",
    nome: "Marcelo Dias",
    telefone: "(19) 99342-8890",
    ultimaHora: "Seg",
    naoLidas: 0,
    atendidoPor: "humano",
    online: false,
    mensagens: [
      { id: "m1", autor: "cliente", texto: "Oi, tudo bem? Queria remarcar nossa call.", hora: "Seg 10:00" },
      { id: "m2", autor: "atendente", texto: "Claro, Marcelo! Que tal quinta às 15h?", hora: "Seg 10:15" },
      { id: "m3", autor: "cliente", texto: "Fechado!", hora: "Seg 10:16" },
    ],
  },
  {
    id: "cv6",
    contatoId: "c5",
    nome: "Camila Rocha",
    telefone: "(11) 97733-0021",
    ultimaHora: "Seg",
    naoLidas: 0,
    atendidoPor: "humano",
    online: true,
    mensagens: [
      { id: "m1", autor: "atendente", texto: "Camila, o onboarding está agendado para amanhã às 10h 😊", hora: "Seg 16:20" },
      { id: "m2", autor: "cliente", texto: "Perfeito, estarei lá. Obrigada!", hora: "Seg 16:31" },
    ],
  },
];
